project:
  type: website

website:
  title: "Proyecto Vainilla UV"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: sandstone
    css: styles.css

editor: visual